eureka:
  instance:
    ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  application:
    name: FOODCART-SERVICE

server:
  port: 8084